// Generate www/css/themes.css from the desktop app's token file.
//
// The mobile chrome wears the same themes as the desktop one, and a theme that
// drifts between them is worse than a theme that is missing: the phone would
// call a colour "Oxford" that Oxford no longer is. So the tokens are copied
// mechanically from src/renderer/css/theme-tokens.css rather than retyped, and
// `npm run check` fails when the copy is stale.
//
//   node scripts/sync-themes.mjs [--check]

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, '..');
const source = path.join(root, '..', 'src', 'renderer', 'css', 'theme-tokens.css');
const target = path.join(root, 'www', 'css', 'themes.css');

// The desktop defines far more tokens than a phone toolbar needs; these are the
// ones the mobile chrome actually paints with.
const TOKENS = [
  '--vex-bg-base', '--vex-bg-elevated', '--vex-bg-deep',
  '--vex-border-subtle', '--vex-border-strong',
  '--vex-accent', '--vex-accent-dim',
  '--vex-text-primary', '--vex-text-secondary', '--vex-text-muted',
  '--vex-success', '--vex-danger'
];

// name → the selector that carries it in the desktop file. :root is Oxford.
const THEMES = [
  ['oxford', ':root', 'Oxford editorial — warm cream, navy'],
  ['graphite', '[data-theme="default"]', 'Graphite & amber — the original Vex'],
  ['midnight', '[data-theme="midnight"]', 'Midnight — near-black, violet'],
  ['forest', '[data-theme="forest"]', 'Forest — deep green'],
  ['ocean', '[data-theme="ocean"]', 'Ocean — deep blue'],
  ['dracula', '[data-theme="dracula"]', 'Dracula'],
  ['nord', '[data-theme="nord"]', 'Nord'],
  ['catppuccin', '[data-theme="catppuccin"]', 'Catppuccin']
];

const css = fs.readFileSync(source, 'utf8');

function ruleBody(selector) {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const match = css.match(new RegExp(escaped + '\\s*\\{(.*?)\\n\\}', 's'));
  return match ? match[1] : '';
}

function readTokens(selector) {
  const body = ruleBody(selector);
  const values = {};
  for (const token of TOKENS) {
    const match = body.match(new RegExp(token.replace(/-/g, '\\-') + '\\s*:\\s*([^;]+);'));
    if (match) values[token] = match[1].trim();
  }
  return values;
}

// Perceived luminance decides whether a theme is dark — it drives the status
// bar style and the page's own color-scheme hint, and a wrong guess there is
// a white flash on every navigation.
function isDark(hex) {
  const match = /^#([0-9a-f]{6})$/i.exec(hex.trim());
  if (!match) return true;
  const value = parseInt(match[1], 16);
  const [r, g, b] = [(value >> 16) & 255, (value >> 8) & 255, value & 255];
  return (0.2126 * r + 0.7152 * g + 0.0722 * b) < 128;
}

const blocks = [];
const registry = [];
for (const [name, selector, label] of THEMES) {
  const values = readTokens(selector);
  const missing = TOKENS.filter(token => !values[token]);
  if (missing.length) {
    console.error('FAIL ' + name + ': theme-tokens.css no longer defines ' + missing.join(', '));
    process.exit(1);
  }
  const dark = isDark(values['--vex-bg-base']);
  registry.push({ id: name, label, dark, accent: values['--vex-accent'], bg: values['--vex-bg-base'] });
  blocks.push('[data-theme="' + name + '"] {\n  color-scheme: ' + (dark ? 'dark' : 'light') + ';\n'
    + TOKENS.map(token => '  ' + token + ': ' + values[token] + ';').join('\n')
    + '\n  --vex-shadow: ' + (dark ? 'rgba(0, 0, 0, 0.55)' : 'rgba(31, 28, 24, 0.20)') + ';'
    + '\n}');
}

const out = '/* Generated by scripts/sync-themes.mjs from src/renderer/css/theme-tokens.css.\n'
  + '   Do not edit by hand — run `npm run themes` after changing a desktop theme.\n'
  + '   ' + THEMES.length + ' themes, the same ones the desktop chrome offers. */\n\n'
  + blocks.join('\n\n') + '\n\n'
  + '/* The registry the theme picker reads, so the list cannot drift from the CSS. */\n'
  + ':root { --vex-themes: "' + registry.map(theme => theme.id).join(' ') + '"; }\n';

const meta = 'window.VEX_THEMES = ' + JSON.stringify(registry, null, 2) + ';\n';
const metaTarget = path.join(root, 'www', 'js', 'themes-data.js');

if (process.argv.includes('--check')) {
  const stale = !fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== out
    || !fs.existsSync(metaTarget) || fs.readFileSync(metaTarget, 'utf8') !== meta;
  if (stale) {
    console.error('FAIL themes.css is stale — run `npm run themes`');
    process.exit(1);
  }
  console.log('ok — themes match the desktop tokens');
} else {
  fs.writeFileSync(target, out);
  fs.writeFileSync(metaTarget, meta);
  console.log('wrote ' + path.relative(root, target) + ' and ' + path.relative(root, metaTarget)
    + ' — ' + registry.length + ' themes');
}
